//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Clima
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbWS_ClimaEntities1 : DbContext
    {
        public dbWS_ClimaEntities1()
            : base("name=dbWS_ClimaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_CLIMA> T_CLIMA { get; set; }
        public DbSet<T_PERSONAS> T_PERSONAS { get; set; }
        public DbSet<T_USUARIOS> T_USUARIOS { get; set; }
    }
}
