//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Clima
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CLIMA
    {
        public int Id_CLIMA { get; set; }
        public Nullable<int> IdUSUARIO_CLIMA { get; set; }
        public string CIUDAD_CLIMA { get; set; }
        public Nullable<byte> TEMPERATURA_CLIMA { get; set; }
        public Nullable<System.DateTime> FECHA_CLIMA { get; set; }
        public string ESTADO_CLIMA { get; set; }
    }
}
