//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Clima
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PERSONAS
    {
        public int Id_PERSONA { get; set; }
        public string IDENT_PERSONA { get; set; }
        public string NOMBRE_PERSONA { get; set; }
        public string CORREO_PERSONA { get; set; }
    }
}
