//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_Prueba.ServiceReferenceClima {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_CLIMA", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class T_CLIMA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_CLIMAField;
        
        private System.Nullable<int> IdUSUARIO_CLIMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIUDAD_CLIMAField;
        
        private System.Nullable<byte> TEMPERATURA_CLIMAField;
        
        private System.Nullable<System.DateTime> FECHA_CLIMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_CLIMAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_CLIMA {
            get {
                return this.Id_CLIMAField;
            }
            set {
                if ((this.Id_CLIMAField.Equals(value) != true)) {
                    this.Id_CLIMAField = value;
                    this.RaisePropertyChanged("Id_CLIMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> IdUSUARIO_CLIMA {
            get {
                return this.IdUSUARIO_CLIMAField;
            }
            set {
                if ((this.IdUSUARIO_CLIMAField.Equals(value) != true)) {
                    this.IdUSUARIO_CLIMAField = value;
                    this.RaisePropertyChanged("IdUSUARIO_CLIMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CIUDAD_CLIMA {
            get {
                return this.CIUDAD_CLIMAField;
            }
            set {
                if ((object.ReferenceEquals(this.CIUDAD_CLIMAField, value) != true)) {
                    this.CIUDAD_CLIMAField = value;
                    this.RaisePropertyChanged("CIUDAD_CLIMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<byte> TEMPERATURA_CLIMA {
            get {
                return this.TEMPERATURA_CLIMAField;
            }
            set {
                if ((this.TEMPERATURA_CLIMAField.Equals(value) != true)) {
                    this.TEMPERATURA_CLIMAField = value;
                    this.RaisePropertyChanged("TEMPERATURA_CLIMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> FECHA_CLIMA {
            get {
                return this.FECHA_CLIMAField;
            }
            set {
                if ((this.FECHA_CLIMAField.Equals(value) != true)) {
                    this.FECHA_CLIMAField = value;
                    this.RaisePropertyChanged("FECHA_CLIMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ESTADO_CLIMA {
            get {
                return this.ESTADO_CLIMAField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_CLIMAField, value) != true)) {
                    this.ESTADO_CLIMAField = value;
                    this.RaisePropertyChanged("ESTADO_CLIMA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_USUARIOS", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class T_USUARIOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLAVE_USUARIOField;
        
        private System.Nullable<int> IdPERSONA_USUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_USUARIO {
            get {
                return this.Id_USUARIOField;
            }
            set {
                if ((this.Id_USUARIOField.Equals(value) != true)) {
                    this.Id_USUARIOField = value;
                    this.RaisePropertyChanged("Id_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOMBRE_USUARIO {
            get {
                return this.NOMBRE_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_USUARIOField, value) != true)) {
                    this.NOMBRE_USUARIOField = value;
                    this.RaisePropertyChanged("NOMBRE_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CLAVE_USUARIO {
            get {
                return this.CLAVE_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.CLAVE_USUARIOField, value) != true)) {
                    this.CLAVE_USUARIOField = value;
                    this.RaisePropertyChanged("CLAVE_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> IdPERSONA_USUARIO {
            get {
                return this.IdPERSONA_USUARIOField;
            }
            set {
                if ((this.IdPERSONA_USUARIOField.Equals(value) != true)) {
                    this.IdPERSONA_USUARIOField = value;
                    this.RaisePropertyChanged("IdPERSONA_USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceClima.WebService_ClimaSoap")]
    public interface WebService_ClimaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerDatosClimaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosClima", ReplyAction="*")]
        WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaResponse ObtenerDatosClima(WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosClima", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaResponse> ObtenerDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerListaDatosClimaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaDatosClima", ReplyAction="*")]
        WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaResponse ObtenerListaDatosClima(WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaDatosClima", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaResponse> ObtenerListaDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObjClima del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarDatosClima", ReplyAction="*")]
        WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaResponse ActualizarDatosClima(WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarDatosClima", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaResponse> ActualizarDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObjClima del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDatosClima", ReplyAction="*")]
        WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaResponse AgregarDatosClima(WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDatosClima", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaResponse> AgregarDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuxLogin", ReplyAction="*")]
        WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginResponse ObtenerUsuxLogin(WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuxLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginResponse> ObtenerUsuxLoginAsync(WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarDatosClima", ReplyAction="*")]
        bool EliminarDatosClima(int idclima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarDatosClima", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarDatosClimaAsync(int idclima);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosClimaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosClima", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequestBody Body;
        
        public ObtenerDatosClimaRequest() {
        }
        
        public ObtenerDatosClimaRequest(WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosClimaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idclima;
        
        public ObtenerDatosClimaRequestBody() {
        }
        
        public ObtenerDatosClimaRequestBody(int idclima) {
            this.idclima = idclima;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosClimaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosClimaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaResponseBody Body;
        
        public ObtenerDatosClimaResponse() {
        }
        
        public ObtenerDatosClimaResponse(WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosClimaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService_Prueba.ServiceReferenceClima.T_CLIMA ObtenerDatosClimaResult;
        
        public ObtenerDatosClimaResponseBody() {
        }
        
        public ObtenerDatosClimaResponseBody(WebService_Prueba.ServiceReferenceClima.T_CLIMA ObtenerDatosClimaResult) {
            this.ObtenerDatosClimaResult = ObtenerDatosClimaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaDatosClimaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaDatosClima", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequestBody Body;
        
        public ObtenerListaDatosClimaRequest() {
        }
        
        public ObtenerListaDatosClimaRequest(WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerListaDatosClimaRequestBody {
        
        public ObtenerListaDatosClimaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaDatosClimaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaDatosClimaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaResponseBody Body;
        
        public ObtenerListaDatosClimaResponse() {
        }
        
        public ObtenerListaDatosClimaResponse(WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerListaDatosClimaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService_Prueba.ServiceReferenceClima.T_CLIMA[] ObtenerListaDatosClimaResult;
        
        public ObtenerListaDatosClimaResponseBody() {
        }
        
        public ObtenerListaDatosClimaResponseBody(WebService_Prueba.ServiceReferenceClima.T_CLIMA[] ObtenerListaDatosClimaResult) {
            this.ObtenerListaDatosClimaResult = ObtenerListaDatosClimaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarDatosClimaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarDatosClima", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequestBody Body;
        
        public ActualizarDatosClimaRequest() {
        }
        
        public ActualizarDatosClimaRequest(WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarDatosClimaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService_Prueba.ServiceReferenceClima.T_CLIMA ObjClima;
        
        public ActualizarDatosClimaRequestBody() {
        }
        
        public ActualizarDatosClimaRequestBody(WebService_Prueba.ServiceReferenceClima.T_CLIMA ObjClima) {
            this.ObjClima = ObjClima;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarDatosClimaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarDatosClimaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaResponseBody Body;
        
        public ActualizarDatosClimaResponse() {
        }
        
        public ActualizarDatosClimaResponse(WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarDatosClimaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarDatosClimaResult;
        
        public ActualizarDatosClimaResponseBody() {
        }
        
        public ActualizarDatosClimaResponseBody(bool ActualizarDatosClimaResult) {
            this.ActualizarDatosClimaResult = ActualizarDatosClimaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDatosClimaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDatosClima", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequestBody Body;
        
        public AgregarDatosClimaRequest() {
        }
        
        public AgregarDatosClimaRequest(WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDatosClimaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService_Prueba.ServiceReferenceClima.T_CLIMA ObjClima;
        
        public AgregarDatosClimaRequestBody() {
        }
        
        public AgregarDatosClimaRequestBody(WebService_Prueba.ServiceReferenceClima.T_CLIMA ObjClima) {
            this.ObjClima = ObjClima;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarDatosClimaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarDatosClimaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaResponseBody Body;
        
        public AgregarDatosClimaResponse() {
        }
        
        public AgregarDatosClimaResponse(WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarDatosClimaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarDatosClimaResult;
        
        public AgregarDatosClimaResponseBody() {
        }
        
        public AgregarDatosClimaResponseBody(bool AgregarDatosClimaResult) {
            this.AgregarDatosClimaResult = AgregarDatosClimaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuxLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuxLogin", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequestBody Body;
        
        public ObtenerUsuxLoginRequest() {
        }
        
        public ObtenerUsuxLoginRequest(WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUsuxLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public ObtenerUsuxLoginRequestBody() {
        }
        
        public ObtenerUsuxLoginRequestBody(string usuario, string clave) {
            this.usuario = usuario;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuxLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuxLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginResponseBody Body;
        
        public ObtenerUsuxLoginResponse() {
        }
        
        public ObtenerUsuxLoginResponse(WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUsuxLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService_Prueba.ServiceReferenceClima.T_USUARIOS ObtenerUsuxLoginResult;
        
        public ObtenerUsuxLoginResponseBody() {
        }
        
        public ObtenerUsuxLoginResponseBody(WebService_Prueba.ServiceReferenceClima.T_USUARIOS ObtenerUsuxLoginResult) {
            this.ObtenerUsuxLoginResult = ObtenerUsuxLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_ClimaSoapChannel : WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_ClimaSoapClient : System.ServiceModel.ClientBase<WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap>, WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap {
        
        public WebService_ClimaSoapClient() {
        }
        
        public WebService_ClimaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_ClimaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ClimaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_ClimaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaResponse WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.ObtenerDatosClima(WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequest request) {
            return base.Channel.ObtenerDatosClima(request);
        }
        
        public WebService_Prueba.ServiceReferenceClima.T_CLIMA ObtenerDatosClima(int idclima) {
            WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequest inValue = new WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequestBody();
            inValue.Body.idclima = idclima;
            WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaResponse retVal = ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).ObtenerDatosClima(inValue);
            return retVal.Body.ObtenerDatosClimaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaResponse> WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.ObtenerDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequest request) {
            return base.Channel.ObtenerDatosClimaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaResponse> ObtenerDatosClimaAsync(int idclima) {
            WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequest inValue = new WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.ObtenerDatosClimaRequestBody();
            inValue.Body.idclima = idclima;
            return ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).ObtenerDatosClimaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaResponse WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.ObtenerListaDatosClima(WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequest request) {
            return base.Channel.ObtenerListaDatosClima(request);
        }
        
        public WebService_Prueba.ServiceReferenceClima.T_CLIMA[] ObtenerListaDatosClima() {
            WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequest inValue = new WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequestBody();
            WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaResponse retVal = ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).ObtenerListaDatosClima(inValue);
            return retVal.Body.ObtenerListaDatosClimaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaResponse> WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.ObtenerListaDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequest request) {
            return base.Channel.ObtenerListaDatosClimaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaResponse> ObtenerListaDatosClimaAsync() {
            WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequest inValue = new WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.ObtenerListaDatosClimaRequestBody();
            return ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).ObtenerListaDatosClimaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaResponse WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.ActualizarDatosClima(WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequest request) {
            return base.Channel.ActualizarDatosClima(request);
        }
        
        public bool ActualizarDatosClima(WebService_Prueba.ServiceReferenceClima.T_CLIMA ObjClima) {
            WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequest inValue = new WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequestBody();
            inValue.Body.ObjClima = ObjClima;
            WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaResponse retVal = ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).ActualizarDatosClima(inValue);
            return retVal.Body.ActualizarDatosClimaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaResponse> WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.ActualizarDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequest request) {
            return base.Channel.ActualizarDatosClimaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaResponse> ActualizarDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.T_CLIMA ObjClima) {
            WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequest inValue = new WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.ActualizarDatosClimaRequestBody();
            inValue.Body.ObjClima = ObjClima;
            return ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).ActualizarDatosClimaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaResponse WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.AgregarDatosClima(WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequest request) {
            return base.Channel.AgregarDatosClima(request);
        }
        
        public bool AgregarDatosClima(WebService_Prueba.ServiceReferenceClima.T_CLIMA ObjClima) {
            WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequest inValue = new WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequestBody();
            inValue.Body.ObjClima = ObjClima;
            WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaResponse retVal = ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).AgregarDatosClima(inValue);
            return retVal.Body.AgregarDatosClimaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaResponse> WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.AgregarDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequest request) {
            return base.Channel.AgregarDatosClimaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaResponse> AgregarDatosClimaAsync(WebService_Prueba.ServiceReferenceClima.T_CLIMA ObjClima) {
            WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequest inValue = new WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.AgregarDatosClimaRequestBody();
            inValue.Body.ObjClima = ObjClima;
            return ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).AgregarDatosClimaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginResponse WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.ObtenerUsuxLogin(WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequest request) {
            return base.Channel.ObtenerUsuxLogin(request);
        }
        
        public WebService_Prueba.ServiceReferenceClima.T_USUARIOS ObtenerUsuxLogin(string usuario, string clave) {
            WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequest inValue = new WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginResponse retVal = ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).ObtenerUsuxLogin(inValue);
            return retVal.Body.ObtenerUsuxLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginResponse> WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap.ObtenerUsuxLoginAsync(WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequest request) {
            return base.Channel.ObtenerUsuxLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginResponse> ObtenerUsuxLoginAsync(string usuario, string clave) {
            WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequest inValue = new WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequest();
            inValue.Body = new WebService_Prueba.ServiceReferenceClima.ObtenerUsuxLoginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.clave = clave;
            return ((WebService_Prueba.ServiceReferenceClima.WebService_ClimaSoap)(this)).ObtenerUsuxLoginAsync(inValue);
        }
        
        public bool EliminarDatosClima(int idclima) {
            return base.Channel.EliminarDatosClima(idclima);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarDatosClimaAsync(int idclima) {
            return base.Channel.EliminarDatosClimaAsync(idclima);
        }
    }
}
